const themes = [
	{
		"id": "weird-scene",
		"pattern": [["noun"], ["gerund"], ["noun"]]
	},
	{
		"id": "gfycat",
		"pattern": [["adjective", "gerund"], ["adjective", "past participle"], ["noun"]]
	},
	{
		"id": "stupid-question",
		"pattern": [["can"], ["plural noun"], ["simple verb"]]
	},
];


const words = {
	// Verbs - Tuple of [simple verb, past participle, gerund]
	"verb": [
		["cook", "cooked", "cooking"],
		["eat", "eaten", "eating"],
		["officiate", "officiated", "officiating"],
	],
	// Nouns - Tuple of [singular noun, plural noun]
	"noun": [
		["cat", "cats"],
		["envelope", "envelopes"],
		["emu", "emus"],
		["orange", "oranges"],
		["ostrich", "ostriches"],
		["organization", "organizations"],
		["officer", "officers"],
	],
	// Adjectives - String
	"adjective": [
		"chief",
		"cabalistic",
		"eager",
		"eager",
		"earless",
		"early",
		"earsplitting",
		"earthbound",
		"earthy",
		"easy",
		"executive",
		"easygoing",
		"eccentric",
		"echoing",
		"ecological",
		"economical",
		"ecstatic",
		"edgy",
		"edible",
		"educated",
		"educational",
		"eerie",
		"effective",
		"effeminate",
		"effortless",
		"elaborate",
		"elastic",
		"electric",
		"electrifying",
		"electromagnetic",
		"electronic",
		"elegant",
		"elemental",
		"elementary",
		"elevated",
		"eligible",
		"elite",
		"elliptical",
		"elongated",
		"elusive",
		"emasculated",
		"embarrassed",
		"embarrassing",
		"embedded",
		"embezzled",
		"emerging",
		"emotional",
		"emotionless",
		"emphasized",
		"emphatic",
		"employable",
		"employed",
		"empowered",
		"empty",
		"enabling",
		"encased",
		"enchanted",
		"enchanting",
		"enclosed",
		"encompassing",
		"encouraged",
		"encouraging",
		"encroaching",
		"oaky",
		"obedient",
		"objectionable",
		"objective",
		"obligatory",
		"obliterated",
		"oblivious",
		"oblong",
		"obnoxious",
		"obscene",
		"obscure",
		"observable",
		"observant",
		"obsessed",
		"obsolete",
		"obstructed",
		"obtrusive",
		"obtuse",
		"obvious",
		"occasional",
		"occupied",
		"odd",
		"odorless",
		"offbeat",
		"offensive",
		"official",
		"offshore",
		"oily",
		"old",
		"olympic",
		"omnidirectional",
		"omnipresent",
		"ongoing",
		"online",
		"oozing",
		"oozy",
		"opaque",
		"open",
		"openhearted",
		"openminded",
		"operating",
		"opinionated",
		"opposable",
		"opposed",
		"opposing",
		"opposite",
		"optical",
		"optimal",
		"optimistic",
		"optional",
		"orange",
		"orchestrated",
		"ordained",
		"ordinary",
		"organic",
		"organized",
		"original",
		"oscillating",
		"outdoorsy",
		"outgoing",
		"overambitious",
		"overanxious",
		"overblown",
		"overcautious",
		"overdone",
		"overdressed",
		"overdue",
		"overeager",
		"overenthusiastic",
		"overexcited",
		"overflowing",
		"overjoyed",
		"overloaded",
		"overlooked",
		"overpowering",
		"overprotective",
		"oversized",
		"oversized",
		"overstuffed",
	],
	// Can-like words - String
	"can": [
		"can",
		"could",
		"can't",
		"couldn't",
	],
}

// Tuple "headers"
words.verb.header = ["simple verb", "past participle", "gerund"];
words.noun.header = ["singular noun", "plural noun"];


export {themes, words}
